### ISSUE TITLE
[MacOS] Crash on startup when launching game using a JDK compiled with newer versions of XCode

### ISSUE THREAD

**Issue by PhilippeDunbar** [DrParadox7/Lost-Era-Modpack#98]
### Your Pack Version

1.6.4

### Type of Instance

Single Player

### Your Actions

Lost era crashes on second launch 
(after asking about textures and optifine) I've tried both optifine and updated textures and neither, so I don't think options matter. 

I've patched my Modrinth launcher to use guava 17 per #94 (It did resolve one bug, I get further now), and I also tried Prism according to @DrParadox7 's suggestion.

I'm happy to use prism or modrinth, I've attached both logs

### Crash Report

Modrinth Log:
https://mclo.gs/NmeACbs

Prism Log:
https://mclo.gs/UkOVfyG

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
This was one hell of a rabbit hole to go through but, from my understanding, there are 2 ways you can attempt to fix this as the end user:
A) Remove Optifine (you'd also need to delete ModDirector so it doesn't get reinstalled)
B) Downgrade Your Java 8 version to one [pre-252](https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=x86-64-bit&package=jdk&show-old-builds=true#zulu)

I'll look into how this can be patched and consult with others that have a deeper understanding than me.

Further read:
https://github.com/MinecraftForge/MinecraftForge/issues/7546

**Comment by DrParadox7** [comment]
Do report back @PhilippeDunbar and once you do get it working, I recommend using the G1C1 garbage collector by adding this to your JVM arguments for improved performance:
`-XX:+UseG1GC -Xms3G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by DrParadox7** [comment]
I pulled out an old mac to debug and test this out.

While the default OpenJDK provided by MultiMC and Modrinth _(Zulu 8.76.0.17 - JRE 8.0.402)_ did crash on startup, the ones in [Adoptium.net](https://adoptium.net/temurin/releases/?version=8) didn't even the latest one worked fine _(Adoptium 8u-402b06 as of writing this)_.

It would be same to assume that Adoptium releases are not built against the latest XCode thus are more resilient to issues like these.

My suggestion is to use Adoptium OpenJDK instead whatever the default launcher provides and the issue should be fixed.

**Comment by PhilippeDunbar** [comment]
Adoptium OpenJDK didnt solve my problem but it seems to work once I removed Optifine. 

(Currently Running with Adoptium JDK & no optifine)

**Comment by PhilippeDunbar** [comment]
I'm including the logs for both working and broken configurations, the working config log also includes a fair amount of gameplay. 

There is some game stuttering with the working configuration, but that may be my fault due to using different memory options then you suggested (due to prism making you use input boxes for memory, and not being able to put memory arguments with the rest of the java args - I just used the memory defaults in the input boxes). I'm currently testing another memory config I'll follow up with how that turns out. 


(working - no optifine, no mod director) https://mclo.gs/q4clMYI

(startup crash - with optifine, no mod director) https://mclo.gs/DziUTGV
